version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  server:
    image: xaimepardalc/asi-herm-deno-app:2.3
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
  app:
    image: xaimepardalc/asi-frontend:1.1
    depends_on:
      - server
    ports:
      - "8080:8080"
  init-container:
    image: alpine
    depends_on:
      - server
    volumes:
      - ./init-mongo.sh:/init-mongo.sh
    command: /bin/sh -c "apk add --no-cache curl && until curl --output /dev/null --silent --head --fail http://server:4000/healhz; do echo waiting for server; sleep 5; done; /bin/sh /init-mongo.sh"

volumes:
  mongodb_data:
